/**
 * @file      sdl_wrapper.hpp
 * @author    Shivang Patel
 * @copyright MIT license
 *
 * @brief DESCRIPTION
 * Header file for the class "Sdl_wrapper". This class act as wrapper of
 * original SDL library for C++. It encaptulates enough functionality
 * from the library for visual of environment, on which
 * BFS has been used, and path it has generated. Information about
 * path and environment, obstacles and space size, will be recieved
 * externally from Obstacle_generator class and this will generate
 * visuals accordingly.
 *
 */

#pragma once

#include "SDL.h"
#include <memory>
#include <utility>
#include <vector>

/**
 * @brief      SDL library wrapper class for visulization of the BFS algorithm
 * through the Bfs class. This class will accept all the information regarding
 * the environment and path for plotting them in nice visuals.
 */
class Sdl_wrapper {
 public:
  /**
   * @brief       A constructor sets width_ and height_ vars of the class.
   *
   * @param[in]   width, height: width and height of the window generated
   * by SDL.
   *
   * @return      none: Return nothing.
   */
  Sdl_wrapper(int width, int height);
  /**
   * @brief       Sets the width_ var of the class.
   *
   * @param[in]   width: width of the window to be generated by SDL.
   *
   * @return      void: Return nothing.
   */
  auto set_width(int width) -> void;
  /**
   * @brief       Getter method to get the
   * width_ var of the class.
   *
   * @return      int: returns width_ var.
   */
  auto get_width(void) -> int;
  /**
   * @brief       Sets the height_ var of the class.
   *
   * @param[in]   height: height of the window generated by SDL.
   *
   * @return      void: Return nothing.
   */
  auto set_height(int height) -> void;
  /**
   * @brief       Getter method to get the
   * width_ var of the class.
   *
   * @return      int: var height_.
   */
  auto get_height(void) -> int;
  /**
   * @brief       Handles events generated by the SDL,  such as
   * close, or mouse related events.
   *
   * @return      void: Return nothing.
   */
  auto event_handler(void) -> int;
  /**
   * @brief       Simple function of updating the SDL generated
   * window or screen.
   *
   * @return      int: 0 in success and -1 in exception.
   */
  auto update_screen(void) -> int;
  /**
   * @brief       Simple function of clearing the SDL generated
   * window or screen with current set color in renderer.
   *
   * @return      int: 0 in success and -1 in exception.
   */
  auto clean(void) -> int;
  /**
   * @brief       Simple function that calls in-build SDL delay.
   *
   * @param[in]   delay: amount of delay in ms (milliseconds).
   *
   * @return      int: 0 in success and -1 in exception.
   */
  auto call_delay(int delay) -> int;
  /**
   * @brief       This function calls SDL functions which can draw Red points
   * on the SDL window or screen at points information passed through params.
   *
   * @param[in]   point: co-ordinate at which point has to draw on SDL window.
   *
   * @return      int: 0 in success and -1 in exception.
   */
  auto draw_point(std::pair<int, int> point) -> int;
  /**
   * @brief       This function calls SDL functions which can draw green points
   * on the SDL window or screen at points information passed through params.
   *
   * @param[in]   point: co-ordinate at which point has to draw on SDL window.
   *
   * @return      int: 0 in success and -1 in exception.
   */
  auto draw_point_path(std::pair<int, int> point) -> int;
  /**
   * @brief       This functions returns the state of the isPolling_ var
   * of the class.
   *
   * @return      bool: True or False.
   */
  auto check_polling_var(void) -> bool;
  /**
   * @brief       This functions sets the state of the isPolling_ var
   * of the class.
   * 
   * @params[in]  state: true or false.
   * 
   * @return      void: Return nothing.
   */
  auto set_polling_var(bool state) -> void;

 private:
  int width_;               ///< width container for SDL window
  int height_;              ///< height container for SDL window
  SDL_Renderer *renderer_;  ///< renderer's raw pointer for SDL window
  SDL_Window *window_;      ///< window's raw pointer for SDL window
  bool isPolling_;          ///< polling var for event hadler function
};
